### ISSUE TITLE
Receive file from server

### ISSUE THREAD

**Issue by hprog2007** [Jamalianpour/EasyFileTransfer#1]
Hi there

Thank you for this easy file transfer library.

I was wondering how can i receive file from server using this library.

Could you help me with this?

Thank you

**Comment by Jamalianpour** [comment]
Hi hprog2007

Could you explain more about your question?
Do you want to receive file with a request or somethings like this?

At all you can use both of server and client on a same machine. it means all of your machine is a server and a client at the same time.

**Comment by hprog2007** [comment]
Hello

Yes, I needed to send a request from client to server and ask for a file
with id number.

Thank you

**Comment by Jamalianpour** [comment]
You need to run server on both machine and after that send your request and receive your response.
but send any things like this request does not contain in this package and you should write your own.
