### ISSUE TITLE
How to "Stop Server"?

### ISSUE THREAD

**Issue by JennyKK22** [Jamalianpour/EasyFileTransfer#2]
I am trying to create a toggle button to start and stop the server. The example code only gives StartServer. The Sample Server does not close properly after closing the form and shows that it is still running. Please share code on how to close the server gracefully. 

Thank you

**Comment by Jamalianpour** [comment]
hello JennyKK22,
server run as a thread so you can terminated server using Abort(); 
like this:
```csharp
EftServer server = new EftServer(@"C:\\", 85);
System.Threading.Thread thread = new System.Threading.Thread(server.StartServer);
thread.Start();    //start
thread.Abort();    //stop

**Comment by JennyKK22** [comment]
Hello, 

 

I did try that with your demo, but the application hangs. Using your demo, is it possible for you to find a way to stop? 

 

Jenny
